<?php 



function oab_stephanie_install() {	
    drupal_set_installed_schema_version('oab_stephanie', 8000);	
}

function oab_stephanie_update_dependencies() {

}

/**
 * RUBYPORTAILOBS-2638 Configuration de password policy
 */
function oab_stephanie_update_8001() {
	include_once("updates/update_8001.inc");
}

/**
 * Configuration d'Autologout
 */
function oab_stephanie_update_8002() {
	include_once("updates/update_8002.inc");
}