axiome_enable_cron: 1
icon_frame_connectivity: Connectivity
icon_frame_teamwork: Teamwork
icon_frame_my_customers: Customers
icon_frame_performance: Flexibility
icon_frame_security: Security
icon_frame_care: Service
icon_frame_tech:  Industry