<?php 



function oab_amel_install() {  
    drupal_set_installed_schema_version('oab_amel', 8000);
}
/**
 *  Création du dashboard manager editorial */

function oab_amel_update_8001() {
    include_once("updates/update_8001.inc");
}

/**
 *  Configuration de la migration des dossiers de presse, communiqués de presse, documents et blogposts */

function oab_amel_update_8002() {
    include_once("updates/update_8002.inc");
}


