<?php

/* field.storage.paragraph.field_home_accroche.yml
paragraphs.paragraphs_type.home_caroussel.yml
field.storage.node.field_caroussel_header.yml */



oabt_YmlImport('field.field.paragraph.home_caroussel.field_home_accroche.yml');
oabt_YmlImport('field.field.paragraph.home_caroussel.field_button.yml');
oabt_YmlImport('field.field.node.homepage.field_caroussel_header.yml');

oabt_YmlImport('core.entity_form_display.node.homepage.default.yml');
oabt_YmlImport('core.entity_view_display.node.homepage.full.yml');
