<?php

oabt_YmlImport('core.entity_form_display.node.customer_story.default.yml');
oabt_YmlImport('core.entity_view_display.node.customer_story.default.yml');
oabt_YmlImport('field.field.node.customer_story.field_top_zone.yml');
oabt_YmlImport('field.field.node.customer_story.field_top_zone_background.yml');
oabt_YmlImport('field.field.node.customer_story.field_top_zone_bg_mobile.yml');
oabt_YmlImport('block.block.topzone.yml');