<?php

/**
 * @file
 * A module that allows embedded entities from the entity_embed module to link
 * to arbitrary URLs.
 */

use Drupal\Core\Extension\ExtensionPathResolver;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Component\Utility\Html;
use Drupal\Component\Serialization\Json;
use Drupal\Component\Utility\UrlHelper;


/**
 * Implements hoook_form_FORM_ID_alter()
 */
function oab_entity_embed_link_form_entity_embed_dialog_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (isset($form['attributes']['data-entity-embed-display-settings'])) {
    $entity_element = $form_state->get('entity_element');
    if (isset($entity_element['data-entity-embed-display-settings']) && !is_array($entity_element['data-entity-embed-display-settings'])) {
      $entity_element['data-entity-embed-display-settings'] = Json::decode($entity_element['data-entity-embed-display-settings']);
    }
    if (isset($form['attributes']['data-entity-embed-display-settings']['image_link'])) {
      $form['attributes']['data-entity-embed-display-settings']['image_link']['#type'] = 'hidden';
      $form['attributes']['data-entity-embed-display-settings']['image_link']['#value'] = '';
    }

    $form['attributes']['data-entity-embed-display-settings']['link_url'] = [
      '#title' => t('Link to'),
      '#description' => t('The URL you would like this item to link to.  Leave blank for none.'),
      '#type' => 'textfield',
      '#default_value' => isset($entity_element['data-entity-embed-display-settings']['link_url'])
        ? Html::decodeEntities($entity_element['data-entity-embed-display-settings']['link_url']) : '',
    ];

        $form['attributes']['data-entity-embed-display-settings']['link_target'] = [
            '#title' => t('Open in new window'),
            '#type' => 'checkbox',
            '#default_value' => isset($entity_element['data-entity-embed-display-settings']['link_target'])
              ? $entity_element['data-entity-embed-display-settings']['link_target'] : '0',
        ];
  }
}

/**
 * Implements hook_theme_registry_alter()
 */
function oab_entity_embed_link_theme_registry_alter(&$theme_registry) {
  /** @var ExtensionPathResolver $service_path_resolver */
  $service_path_resolver = \Drupal::service('extension.path.resolver');

  $theme_registry['entity_embed_container']['path'] = $service_path_resolver->getPath('module', 'oab_entity_embed_link') . '/templates';
}

/**
 * Implemets hook_preprocess_HOOK()
 */
function oab_entity_embed_link_preprocess_entity_embed_container(&$variables) {
  $variables['url'] = isset($variables['element']['#context']['data-entity-embed-display-settings']['link_url'])
    ? UrlHelper::filterBadProtocol($variables['element']['#context']['data-entity-embed-display-settings']['link_url']) : '';
  $variables['target'] = isset($variables['element']['#context']['data-entity-embed-display-settings']['link_target'])
    ? UrlHelper::filterBadProtocol($variables['element']['#context']['data-entity-embed-display-settings']['link_target']) : '';
}
