<?php


function oab_cookie_compliance_theme($existing, $type, $theme, $path) {

    $theme = array();
    $theme['block__cookie_compliance_block'] = array(
            'variables' => array(
                'message' => 'Default message',
                'link_text' => 'Default link text',
                'link_url'  => 'Default url',
                'bla'   => "blu",
            ),
            'template'  => 'block--cookie-compliance-block',
    );
    return $theme;
}
