<?php


oabt_YmlImport('core.entity_form_display.node.custom_page.default.yml');
oabt_YmlImport('core.entity_form_display.node.customer_story.default.yml');
oabt_YmlImport('core.entity_form_display.node.full_html.default.yml');
oabt_YmlImport('core.entity_form_display.node.industry.default.yml');
oabt_YmlImport('core.entity_form_display.node.magazine.default.yml');
oabt_YmlImport('core.entity_form_display.node.partner.default.yml');
oabt_YmlImport('core.entity_form_display.node.press_kit.default.yml');
oabt_YmlImport('core.entity_form_display.node.press_release.default.yml');
oabt_YmlImport('core.entity_form_display.node.simple_page.default.yml');
oabt_YmlImport('core.entity_form_display.node.solution.default.yml');
oabt_YmlImport('core.entity_form_display.node.blog_post.default.yml');
oabt_YmlImport('core.entity_form_display.node.product.default.yml');
