<?php

/**
 * @file
 * Contains oab_mp_product_formule_packages.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function oab_mp_product_formule_packages_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the oab_mp_product_formule_packages module.
    case 'help.page.oab_mp_product_formule_packages':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Manage the packages of Product Formules') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function oab_mp_product_formule_packages_theme() {
  $theme = [];
  $theme['formule_package'] = [
    'render element' => 'elements',
    'file' => 'formule_package.page.inc',
    'template' => 'formule_package',
  ];
  $theme['formule_package_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'formule_package.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function oab_mp_product_formule_packages_theme_suggestions_formule_package(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#formule_package'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'formule_package__' . $sanitized_view_mode;
  $suggestions[] = 'formule_package__' . $entity->bundle();
  $suggestions[] = 'formule_package__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'formule_package__' . $entity->id();
  $suggestions[] = 'formule_package__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
