<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\oab_akamai\Form\OabAkamaiForm;

function oab_akamai_testDrushAkamai($form,FormStateInterface &$form_state) {
    $url_to_test = $form_state->getValue('test_url');
    $host = $form_state->getValue('test_host');

    $akamaiCtrl = new \Drupal\oab_akamai\Controller\OabAkamaiController();

    $akamaiCtrl->flushAkamai($url_to_test);
    $akamaiCtrl->flushVarnish($url_to_test, $host);
    $akamaiCtrl->flushDrupalCache($url_to_test);

}

/**
 * Hook sur les nodes à la modification
 *  -> Si l'option est activée dans la config, on vide tous les caches
 */
function oab_akamai_node_update(Drupal\Core\Entity\EntityInterface $node) {
    $config = \Drupal::config(OabAkamaiForm::getConfigName());
    $hook_enabled = $config->get('enable_hook');

    #Si la conf est activée, on vire les caches
    if ($hook_enabled) {

        # On recupère l'URL du noeud et le host du site
        $node_url = $node->toUrl()->setAbsolute()->toString();
        $host = \Drupal::request()->getHost();


        $akamaiCtrl = new \Drupal\oab_akamai\Controller\OabAkamaiController();

        $akamaiCtrl->flushAkamai($node_url);
        $akamaiCtrl->flushVarnish($node_url, $host);
        $akamaiCtrl->flushDrupalCache($node_url);

    }
}
