<?php

use Drupal\Core\Menu\MenuLinkInterface;
use Drupal\menu_link_content\Entity\MenuLinkContent;

/**
 * Implements hook_form_alter().
 */
function oab_frontoffice_form_alter(&$form, Drupal\Core\Form\FormState &$form_state) {
  if (isset($form['#form_id'])) {
    if ($form['#form_id'] == 'contact_message_any_request_form') {
      if (isset($form['name'])){
        $form['name']['#title'] = t('Your last name');
      }
      if (isset($form['mail'])){
        $form['mail']['#title'] = t('Your email address');
      }
      
      unset($form['actions']['preview']);
    }
  }
}

function oab_frontoffice_preprocess_menu(&$variables) {
  if (isset($variables['items'])
  && is_array($variables['items'])) {
    foreach ($variables['items'] as &$item) {
      $menuLinkEntity = oab_frontoffice_load_link_entity_by_link($item['original_link']);
      if (!empty($menuLinkEntity)) {
        $menu_uri = $menuLinkEntity->link->first()->uri;

        // gestion des liens <front>
        $languages = \Drupal::languageManager()->getLanguages();
        foreach($languages AS $key => $value){
          $langcode = $value->getId();
          if ($menu_uri === 'internal:/<front_' . $langcode . '>'){
            \Drupal::languageManager()->setConfigOverrideLanguage(\Drupal::languageManager()->getLanguage($langcode));
            $new_url = \Drupal\Core\Url::fromRoute('<front>', array(), array('language' => $value));
            $item['url'] = $new_url;
          }
        }

        if (!empty($menuLinkEntity->link->first()->options['target'])) {
          $item['url']->setOption('target', $menuLinkEntity->link->first()->options['target']);
        }
      }
    }
  }
}

function oab_frontoffice_load_link_entity_by_link(MenuLinkInterface $menuLinkContentPlugin) {
  $entity = NULL;
  if ($menuLinkContentPlugin instanceof Drupal\menu_link_content\Plugin\Menu\MenuLinkContent) {
    list($entity_type, $uuid) = explode(':', $menuLinkContentPlugin->getPluginId(), 2);
    $entity = \Drupal::entityManager()->loadEntityByUuid($entity_type, $uuid);
  }
  return $entity;
}