<?php

function oab_will_install() {
    drupal_set_installed_schema_version('oab_will', 8000);
}


/** Définit l'ordre des updates par rapport aux autres modules
 * @return mixed
 */
function oab_will_update_dependencies() {
    $dependencies = array();
	return $dependencies;
}

/**
 * RUBYPORTAILOBS-2739 Rajout champ contributeur externe au user
 */

function oab_will_update_8001() {
  include_once("updates/update_8001.inc");
}


