tac_lite_categories:
  hub: hub
tac_lite_schemes: '2'
menu_rebuild_needed: true
_core:
  default_config_hash: O3rsbjEveBvnof1Hdq3ih8UBqlRN2betEk9OZhaiTPM
tac_lite_config_scheme_1:
  name: view
  perms:
    grant_view: grant_view
  unpublished: 0
  term_visibility: 0
  tac_lite_create: 0
tac_lite_grants_scheme_1:
  anonymous:
    hub:
      0: '0'
  authenticated:
    hub:
      0: '0'
  administrator:
    hub: {  }
  chief_editor:
    hub: {  }
  digital_admin:
    hub: {  }
  webform_manager:
    hub: {  }
  contributor:
    hub: {  }
  fh_backbones:
    hub: {  }
  dvi:
    hub: {  }
  hub_editor:
    hub: {  }
tac_lite_config_scheme_2:
  name: 'update and delete'
  perms:
    grant_update: grant_update
    grant_delete: grant_delete
  unpublished: 0
  term_visibility: 1
  tac_lite_create: 1
tac_lite_grants_scheme_2:
  anonymous:
    hub: {  }
  authenticated:
    hub: {  }
  administrator:
    hub: {  }
  chief_editor:
    hub: {  }
  digital_admin:
    hub: {  }
  webform_manager:
    hub: {  }
  contributor:
    hub: {  }
  fh_backbones:
    hub: {  }
  dvi:
    hub: {  }
  hub_editor:
    hub: {  }