oab_cookie_compliance.cookie_compliance_settings:
  title: 'OAB Cookie compliance Settings'
  base_route_name: oab_cookie_compliance.cookie_compliance.settings
  names:
    - oab_cookie_compliance.cookie_compliance
