pm-enable -y roleassign
pm-enable -y password_policy
pm-enable -y password_policy_character_types
pm-enable -y password_policy_characters
pm-enable -y password_policy_history
pm-enable -y password_policy_length
pm-enable -y password_policy_username
pm-enable -y oab_tibo
pm-enable -y views_infinite_scroll
pm-enable -y oab_user_access_rights
pm-enable -y oab_entity_embed_link
pm-enable -y oab_yassine
pm-enable -y oab_migrate_content
pm-enable -y oab_tristan
pm-enable -y entity_reference_revisions
pm-enable -y paragraphs
updatedb
#entity-updates