<?php

/**
 * Implements hook_node_delete().
 */
function oab_synomia_search_flux_node_delete($node) {

	$base_url = \Drupal::request()->getSchemeAndHttpHost();
	//lors de la suppression d'un node, on enregistre l'url et l'id du node supprimé pour le transmettre au sitemap Synomia
	$deleted_content = new \Drupal\oab_synomia_search_flux\Classes\SynomiaDeletedContent();
	$deleted_content->setNid($node->nid);
	$deleted_content->setContentType($node->type);
	$deleted_content->setLanguage($node->language());
	$deleted_content->setUrl($node->toUrl());
	/*
	if($node->language != 'und')
	{
		$deleted_content->url = '/'.$node->language.'/'.drupal_get_path_alias("node/" . $node->nid , $node->language);
	}
	else {
		$deleted_content->url = drupal_get_path_alias("node/" . $node->nid);
	}
	*/
	$deleted_content->setDeleted(time());
	//$deleted_content->save();
	oabt($deleted_content); exit;
}