<?php

// Affichage des dates au format EN
oabt_YmlImport('views.view.home_eclairage_playlist.yml');

//  affichage des dates au format EN
oabt_YmlImport('views.view.page_thematique.yml');


// creation des menus Top Right Navbar Footer pour chaque langue
oabt_YmlImport('system.menu.top-right-navbar-footer-en.yml');
oabt_YmlImport('system.menu.top-right-navbar-footer-fr.yml');
oabt_YmlImport('system.menu.top-right-navbar-footer-ru.yml');
oabt_YmlImport('system.menu.top-right-navbar-footer-rue.yml');

// Placement des blocs
oabt_YmlImport('block.block.toprightnavbarfooterruen.yml');
oabt_YmlImport('block.block.toprightnavbarfooterru.yml');
oabt_YmlImport('block.block.toprightnavbarfooterfr.yml');
oabt_YmlImport('block.block.toprightnavbarfooteren.yml');

