<?php


function oab_password_policy_alter_form_user_form_alter(&$form, &$form_state) {
  // Add the submit handler.
  oabt("bla");oabt($form['actions']['submit']["#submit"]);
  $form['actions']['submit']['#submit'][] = '_password_policy_user_profile_form_submit';
  oabt($form['actions']['submit']["#submit"]);
}


/**
 * Implements hook_module_implements_alter().
 */
function oab_password_policy_alter_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_user_form_alter') {
    oabt($hook);
    oabt($implementations);
    if (isset($implementations['oab_password_policy_alter'])) {
      ##Je l'enlève pour le remettre en dernier
      $group = $implementations['oab_password_policy_alter'];
      unset($implementations['oab_password_policy_alter']);
      $implementations['oab_password_policy_alter'] = $group;
    }
    oabt($implementations);
  }
  return $implementations;
}