<?php


function oab_password_policy_alter_form_user_form_alter(&$form, &$form_state) {
  // Add the submit handler.
  if (false !== ($key =
      array_search('_password_policy_user_profile_form_submit',
        $form['actions']['submit']['#submit'])
    )) {
    ## Si la fonction de Password Policy est dans le tableau,
    ## Je la supprime pour la remettre en dernière
    ## Par défaut, PP la place en 1er du tableau et certains éléments, comme l'uid
    ## ne sont chargés que par des fonctions Drupal qui passent après celle-là
    ## et qui empeche la MAJ de l'expiration d'un MDP
    unset($form['actions']['submit']['#submit'][$key]);
    $form['actions']['submit']['#submit'][] = '_password_policy_user_profile_form_submit';
  }
}


/**
 * Implements hook_module_implements_alter().
 */
function oab_password_policy_alter_module_implements_alter(&$implementations, $hook) {
  ##Juste je fais passer mon alter en dernier pour être qu'il soit appelé après celui de PP
  if ($hook == 'form_user_form_alter') {
    if (isset($implementations['oab_password_policy_alter'])) {
      ##Je l'enlève pour le remettre en dernier
      $group = $implementations['oab_password_policy_alter'];
      unset($implementations['oab_password_policy_alter']);
      $implementations['oab_password_policy_alter'] = $group;
    }
  }
  return $implementations;
}