<?php

/**
 * Implements hook_form_alter().
 */
use Drupal\Core\Form\FormStateInterface;
use Drupal\editor\Entity\Editor;
use Drupal\Core\Url;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Database\Database;
use Drupal\image\Entity\ImageStyle;
use \Drupal\file\Entity\File;

function oab_will_form_alter(&$form, FormStateInterface $form_state, $form_id) {
    $user = \Drupal::currentUser();
    $user_id = $user->id();

  $current_language = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $languages = \Drupal::languageManager()->getLanguages();
  $current_user_language = Drupal::currentUser()->getPreferredLangcode();

  $edit_form = FALSE;

  //R-3177 suppression des formats systeme pour les non admin
  if ($form_id=="entity_embed_dialog") {
     if ($user_id <> 1) {
        unset($form['attributes']['data-entity-embed-display-settings']['image_style']['#options']["document_visual_image"]);
        unset($form['attributes']['data-entity-embed-display-settings']['image_style']['#options']["file_entity_browser_thumbnail"]);
        unset($form['attributes']['data-entity-embed-display-settings']['image_style']['#options']["homepage_expertise"]);
        unset($form['attributes']['data-entity-embed-display-settings']['image_style']['#options']["homepage_news"]);
        unset($form['attributes']['data-entity-embed-display-settings']['image_style']['#options']["homepage_solution_banner"]);
        unset($form['attributes']['data-entity-embed-display-settings']['image_style']['#options']["homepage_top_zone"]);
        unset($form['attributes']['data-entity-embed-display-settings']['image_style']['#options']["linkit_result_thumbnail"]);
        unset($form['attributes']['data-entity-embed-display-settings']['image_style']['#options']["max_1300x1300"]);
        unset($form['attributes']['data-entity-embed-display-settings']['image_style']['#options']["max_2600x2600"]);
        unset($form['attributes']['data-entity-embed-display-settings']['image_style']['#options']["playlist"]);
        unset($form['attributes']['data-entity-embed-display-settings']['image_style']['#options']["related_contents"]);
        unset($form['attributes']['data-entity-embed-display-settings']['image_style']['#options']["subhome"]);
        unset($form['attributes']['data-entity-embed-display-settings']['image_style']['#options']["top_zone"]);
        unset($form['attributes']['data-entity-embed-display-settings']['image_style']['#options']["top_zone_big"]);
        unset($form['attributes']['data-entity-embed-display-settings']['image_style']['#options']["valorisation"]);
     }
  }

    if ($form_id=="views_exposed_form") {
        switch ($form['#id']) {
            case "views-exposed-form-content-page-1":

//                $form['field_profile_target_id']['#autocomplete_route_name'] = 'views_autocomplete_api';
//                $form['field_profile_target_id']['#autocomplete_route_parameters'] = array('view_name' => 'autocomplete','display_id'=>'block_1');
//                $form['#validate'][] = 'views_exposed_form_content_page_1_form_validate';

                break;
            default:
            break;
        }
    }
}

function views_exposed_form_content_page_1_form_validate($form, FormStateInterface &$form_state) {
    $values = $form_state->getValue('field_profile_target_id');
    if (isset($values) && $values <> "") {
        $tab_values = explode(" | ", $values);
        $form_state->setValue('field_profile_target_id', $tab_values[1]);
    }
}
