cookie_compliance.settings:
  type: config_object
  label: 'Cookie compliance ddd'
  mapping:
    cookie_text:
      type: label
      label: 'Block text'
    cookie_link_text:
      type: label
      label: 'Link text'
    cookie_link:
      type: label
      label: 'Link URL'
