<?php

use Drupal\Core\File\FileUrlGenerator;
use Drupal\media\Entity\Media;

define("BACKGROUND_FIELD_VISIBILITY", 'field_visibility');

function oab_background_image_media_insert(Media $entity) {
    if ($entity->bundle() !== 'background') {
        return;
    }

    /** @var Drupal\oab_background_image\Services\BgImageManagementInterface $bg_cache_service */
    $bg_cache_service = \Drupal::service('oab_background_image.bg_image_management');


    if ($entity->isPublished()) {
        $field_value = Drupal::service('oab_background_image.entity_get_field')->getFirst($entity, BACKGROUND_FIELD_VISIBILITY);

        foreach (_oab_background_image_get_urls($field_value) as $url) {
            $bg_cache_service->add($url, $entity);
        }
    }
}

function oab_background_image_media_update(Media $entity) {

    if ($entity->bundle() !== 'background') {
        return;
    }

    /** @var Drupal\oab_background_image\Services\BgImageManagementInterface $bg_cache_service */
    $bg_cache_service = \Drupal::service('oab_background_image.bg_image_management');

    if ($entity->isPublished()) {

        /** @var Drupal\Core\Field\FieldItemList $field_visibility */
        $field_value = Drupal::service('oab_background_image.entity_get_field')->getFirst($entity, BACKGROUND_FIELD_VISIBILITY);

        foreach (_oab_background_image_get_urls($field_value) as $url) {
            $bg_cache_service->add($url, $entity);
        }


    } elseif (isset($entity->original)) {
        /** @var Media $original */
        $original = $entity->original;

        // Si l'ancien était publié, on supp pour toutes les URLs
        if ($original->isPublished()) {
            $field_value = Drupal::service('oab_background_image.entity_get_field')->getFirst($entity, BACKGROUND_FIELD_VISIBILITY);
            foreach (_oab_background_image_get_urls($field_value) as $url) {
                $bg_cache_service->remove($url);
            }
        }

    }
}


/**
 * Implements hook_entity_predelete().
 */
function oab_background_image_media_delete(Media $entity) {

    if ($entity->bundle() !== 'background') {
        return;
    }

    /** @var Drupal\oab_background_image\Services\BgImageManagementInterface $bg_cache_service */
    $bg_cache_service = \Drupal::service('oab_background_image.bg_image_management');

    /** @var Media $original */
    $field_value = Drupal::service('oab_background_image.entity_get_field')->getFirst($entity, BACKGROUND_FIELD_VISIBILITY);

    foreach (_oab_background_image_get_urls($field_value) as $url) {
        $bg_cache_service->remove($url);
    }
}



function oab_background_image_preprocess_html(&$variables) {
    $path = \Drupal::request()->getPathInfo();

    /** @var Media $background */
    $background = \Drupal::service('oab_background_image.bg_image_management')->get($path);

    if ($background !== null && $background->isPublished() && isset($background->field_image->entity)) {

      /** @var FileUrlGenerator  $service_generate_url */
      $service_generate_url = \Drupal::service('file_url_generator');

      $file_url = $service_generate_url->generateString($background->field_image->entity->getFileUri());

        if ($file_url !== false) {
            if (!isset($variables['attributes']['style'])) {
                $variables['attributes']['style'] = "";
            }

            if (!isset($variables['attributes']['class'])) {
                $variables['attributes']['class'] = [];
            }
            $variables['attributes']['class'][] = "oab_background_image";
            $variables['attributes']['style'] .= "; background-image: url('". $file_url ."'); background-repeat: no-repeat; background-attachment: fixed; background-size: cover; -o-background-size: cover; -moz-background-size: cover; -webkit-background-size:cover; background-color:transparent;";

        }
    }
}



function _oab_background_image_get_urls($field_value) {
    $ret = [];
    if (isset($field_value['value'])) {
        $ret = explode("\r\n", $field_value['value']);
    }

    return $ret;
}
