idp:
  federation_identite_orange_bus: federation_identite_orange_bus
logout: false
logged_in_redirect: ''
update_email: false
update_language: false
no_account_authenticated_user_role: false
no_account_authenticated_user_account: null
force_authentication: false
force_saml_only: false
account_request_request_account: false
