contact:
  technical:
    name: ''
    email: ''
  support:
    name: ''
    email: ''
organization:
  name: ''
  display_name: ''
  url: ''
strict: true
security:
  nameIdEncrypted: false
  authnRequestsSigned: false
  logoutRequestSigned: false
  logoutResponseSigned: false
  wantMessagesSigned: false
  wantAssertionsSigned: true
  wantNameIdEncrypted: false
  signMetaData: false
  signatureAlgorithm: 'http://www.w3.org/2000/09/xmldsig#rsa-sha1'
  lowercaseUrlencoding: false
cert_location: /var/www/html/.saml_cert/certificate.crt
key_location: /var/www/html/.saml_cert/privateKey.key
new_cert_location: ''
entity_id: 'https://uat.www.orange-business.com/'
debug: false
nameIdEncrypted: false
authnRequestsSigned: false
logoutRequestSigned: false
logoutResponseSigned: false
wantMessagesSigned: false
wantAssertionsSigned: false
wantNameIdEncrypted: false
signMetaData: false
signatureAlgorithm: 'http://www.w3.org/2000/09/xmldsig#rsa-sha1'
lowercaseUrlencoding: false
assertion_urls: 'https://uat.www.orange-business.com/saml/consume'
