# Field for image on top of homepage
uuid: 5f058246-6b49-4623-b4ce-b44c713b3b39
langcode: en
status: true
dependencies:
  module:
    - file
    - image
    - node
id: node.field_top_zone_image_mobile
field_name: field_top_zone_image_mobile
entity_type: node
type: image
settings:
  uri_scheme: public
  default_image:
    uuid: ''
    alt: ''
    title: ''
    width: null
    height: null
  target_type: file
  display_field: false
  display_default: false
module: image
locked: false
cardinality: 1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
