settings:
  default_form_exception_message: 'Impossible d''afficher ce formulaire. Veuillez contacter l''administrateur du site'
  default_submit_button_label: Valider
  default_reset_button_label: 'Remise à zéro'
  default_wizard_prev_button_label: '< Page précédente'
  default_wizard_next_button_label: 'Page suivante >'
  default_preview_next_button_label: Prévisualisation
  default_preview_prev_button_label: '< Précédent'
  default_preview_label: Prévisualisation
  default_draft_button_label: 'Sauvegarder le brouillon'
  default_confirmation_back_label: 'Retour au formulaire'
element:
  default_more_title: Plus
