<?php

// on met à jour la vue subhomes car fuckée précédemment
oabt_YmlImport('views.view.subhomes.yml');

// on remplit les descriptions des taxos subhomes FR
oabt_taxoAddDescription(297, '<p>Engager la discussion sur les défis, les opportunités et les impacts du digital pour l’entreprise, c’est le but visé par nos blogs que nous voulons ouverts et curieux… Dites-nous si nous avons réussi ! ;-)</p>');
oabt_taxoAddDescription(209, '<p>Pour répondre à vos besoins, vous fournir les solutions les plus efficaces et un accès simple aux meilleures technologies, nous avons construit des alliances avec les fournisseurs mondiaux les plus performants et disposant des plus hauts niveaux de certification.</p>');
oabt_taxoAddDescription(210, '<p>Avec nos clients, nous écrivons ensemble une histoire. Pour évoquer cette aventure humaine, ils prennent la parole et nous livrent leurs témoignages.</p>');
oabt_taxoAddDescription(211, '<p>Retrouvez sur cette page les dossiers, les communiqués de presse ainsi que toutes les informations relatives à l\'actualité d\'Orange Business Services.</p>');
oabt_taxoAddDescription(212, '<p>Vous voulez vous informer sur le cloud, la connectivité enrichie ou la transformation digitale de l’entreprise ? Consultables d’un clic, brochures et Livres blancs vous offrent toutes les clés pour comprendre les évolutions de votre secteur.</p>');
oabt_taxoAddDescription(213, '<p>Que vous soyez une PME, une ETI, une grande entreprise ou une multinationale, nous mettons à votre disposition des solutions digitales adaptées à vos besoins pour vous aider à développer vos activités. Découvrez-les.</p>');
oabt_taxoAddDescription(214, '<p>À travers des articles sur toutes les nouvelles tendances de l’innovation digitale au service de l’entreprise, découvrez les expertises d\'Orange Business Services.</p>');

// on remplit les descriptions des taxos subhomes EN
oabt_taxoAddDescription(405, '<p>Sit back and take a read as our bloggers discuss the challenges, opportunities and impacts of digital technology on business. You’ll find all of their latest musings here.</p>');
oabt_taxoAddDescription(407, '<p>Whether you’re a small, mid-sized, large or multinational business, we have the digital solutions that fit your needs and can help transform your business.</p>');
oabt_taxoAddDescription(215, '<p>To meet your needs, to provide you with the most efficient solutions and to give you easy access to the best technologies, we’ve built alliances with the world\'s best-performing technology providers with the highest levels of certification.</p>');
oabt_taxoAddDescription(216, '<p>Together with our customers, we create stories. These human adventures begin as they take the floor and share their experiences.</p>');
oabt_taxoAddDescription(217, '<p>Here you’ll find press releases and other news and information about Orange Business Services.</p>');
oabt_taxoAddDescription(218, '<p>Want to learn about the cloud, enriched connectivity or digital transformation? Our brochures and white papers provide the keys to understanding how the latest technologies and innovations will affect your business.</p>');
oabt_taxoAddDescription(220, '<p>Browse through these articles to learn about all the new trends in digital innovation in B2B as well as the Orange Business Services expertise in these areas.</p>');