session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: en
    fr: fr
    ru: ru
    es: es
    ru-en: ru-en
    pt-br: br
  domains:
    en: ''
    fr: ''
    ru: ''
    es: ''
    ru-en: ''
    pt-br: ''
selected_langcode: site_default
_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
