<?php

function get_correspondances_categoriesMagazineD7_to_MagazineFormatD8() {
    $correspondances =
        array(
            //EN
            '649' => array('tid_d7' => '649', 'label_d7' => 'business', 'langcode' => 'en', 'label_d8' => 'Article', 'tid_D8' => ''),
            '659' => array('tid_d7' => '659', 'label_d7' => 'case studies', 'langcode' => 'en', 'label_d8' => 'Case study', 'tid_D8' => ''),
            '661' => array('tid_d7' => '661', 'label_d7' => 'news & events', 'langcode' => 'en', 'label_d8' => 'Article', 'tid_D8' => ''),
            '34792' => array('tid_d7' => '34792', 'label_d7' => 'Newsletter', 'langcode' => 'en', 'label_d8' => 'Article', 'tid_D8' => ''),
            '663' => array('tid_d7' => '663', 'label_d7' => 'opinion', 'langcode' => 'en', 'label_d8' => 'Article', 'tid_D8' => ''),
            '647' => array('tid_d7' => '647', 'label_d7' => 'solutions', 'langcode' => 'en', 'label_d8' => 'Article', 'tid_D8' => ''),
            '660' => array('tid_d7' => '660', 'label_d7' => 'technology', 'langcode' => 'en', 'label_d8' => 'Article', 'tid_D8' => ''),
            //FR
            '16391' => array('tid_d7' => '16391', 'label_d7' => 'l\'info', 'langcode' => 'fr', 'label_d8' => 'Actualités', 'tid_D8' => ''),
            '16395' => array('tid_d7' => '16395', 'label_d7' => 'pratique', 'langcode' => 'fr', 'label_d8' => 'Bonnes pratiques', 'tid_D8' => ''),
            '16394' => array('tid_d7' => '16394', 'label_d7' => 'regards métiers', 'langcode' => 'fr', 'label_d8' => 'Experts', 'tid_D8' => ''),
            '16393' => array('tid_d7' => '16393', 'label_d7' => 'témoignages', 'langcode' => 'fr', 'label_d8' => 'Témoignages', 'tid_D8' => ''),
            '16392' => array('tid_d7' => '16392', 'label_d7' => 'tendances', 'langcode' => 'fr', 'label_d8' => 'Tendances', 'tid_D8' => ''),
        );
    return $correspondances;
}
