<?php

function get_correspondances_regionsD7_to_regionsD8() {
    $regions =
        array(
            '26455' => array('tid_d7' => '26455', 'label_d7' => 'Africa', 'langcode' => 'en', 'label_d8' => 'Middle East & Africa', 'tid_D8' => ''),
            '16780' => array('tid_d7' => '16780', 'label_d7' => 'Asia Pacific', 'langcode' => 'en', 'label_d8' => 'Asia Pacific', 'tid_D8' => ''),
            '16793' => array('tid_d7' => '16793', 'label_d7' => 'Europe', 'langcode' => 'en', 'label_d8' => 'Europe', 'tid_D8' => ''),
            '16794' => array('tid_d7' => '16794', 'label_d7' => 'Latin America', 'langcode' => 'en', 'label_d8' => 'Latin America', 'tid_D8' => ''),
            '16795' => array('tid_d7' => '16795', 'label_d7' => 'Middle East', 'langcode' => 'en', 'label_d8' => 'Middle East & Africa', 'tid_D8' => ''),
            '16796' => array('tid_d7' => '16796', 'label_d7' => 'North America', 'langcode' => 'en', 'label_d8' => 'North America', 'tid_D8' => ''),
            '25003' => array('tid_d7' => '25003', 'label_d7' => 'Russia', 'langcode' => 'en', 'label_d8' => 'Russia', 'tid_D8' => ''),
            '35102' => array('tid_d7' => '35102', 'label_d7' => 'Equant Ä°stanbul Telekom A.Åž.', 'langcode' => 'en', 'label_d8' => '', 'tid_D8' => ''),
        );
    return $regions;

}
