<?php

function get_correspondances_soltutionD7_to_solutionD8 () {
    $solutions =
        array(
            //Solutions EN
            '32332' => array('tid_d7' => '32332', 'label_d7' => 'big data & analytics', 'langcode' => 'en', 'label_d8' => '', 'tid_D8' => ''),
            '16347' => array('tid_d7' => '16347', 'label_d7' => 'Cloud computing', 'langcode' => 'en', 'label_d8' => 'Flexible IT', 'tid_D8' => ''),
            '35313' => array('tid_d7' => '35313', 'label_d7' => 'Collaborative workspace', 'langcode' => 'en', 'label_d8' => 'Collaborative Workspace', 'tid_D8' => ''),
            '16790' => array('tid_d7' => '16790', 'label_d7' => 'conferencing', 'langcode' => 'en', 'label_d8' => 'Collaborative Workspace', 'tid_D8' => ''),
            '35131' => array('tid_d7' => '35131', 'label_d7' => 'Connectivity', 'langcode' => 'en', 'label_d8' => 'Enriched connectivity', 'tid_D8' => ''),
            '35028' => array('tid_d7' => '35028', 'label_d7' => 'Consulting', 'langcode' => 'en', 'label_d8' => 'Services', 'tid_D8' => ''),
            '35187' => array('tid_d7' => '35187', 'label_d7' => 'Customer experience', 'langcode' => 'en', 'label_d8' => 'Enriched Customer relationships', 'tid_D8' => ''),
            '35144' => array('tid_d7' => '35144', 'label_d7' => 'Digital transformation', 'langcode' => 'en', 'label_d8' => 'Services', 'tid_D8' => ''),
            '35145' => array('tid_d7' => '35145', 'label_d7' => 'Digital Transformation eBook Asset Landing Page', 'langcode' => 'en', 'label_d8' => '', 'tid_D8' => ''),
            '35072' => array('tid_d7' => '35072', 'label_d7' => 'Digital workspace', 'langcode' => 'en', 'label_d8' => 'Collaborative Workspace', 'tid_D8' => ''),
            '16788' => array('tid_d7' => '16788', 'label_d7' => 'Internet of Things', 'langcode' => 'en', 'label_d8' => 'Business Innovation', 'tid_D8' => ''),
            '35219' => array('tid_d7' => '35219', 'label_d7' => 'IoT and data analytics', 'langcode' => 'en', 'label_d8' => 'Business Innovation', 'tid_D8' => ''),
            '16390' => array('tid_d7' => '16390', 'label_d7' => 'mobility', 'langcode' => 'en', 'label_d8' => 'Collaborative Workspace', 'tid_D8' => ''),
            '16382' => array('tid_d7' => '16382', 'label_d7' => 'Network', 'langcode' => 'en', 'label_d8' => 'Enriched connectivity', 'tid_D8' => ''),
            '35011' => array('tid_d7' => '35011', 'label_d7' => 'Powerpage template sample', 'langcode' => 'en', 'label_d8' => '', 'tid_D8' => ''),
            '24726' => array('tid_d7' => '24726', 'label_d7' => 'professional services', 'langcode' => 'en', 'label_d8' => '', 'tid_D8' => ''),
            '16789' => array('tid_d7' => '16789', 'label_d7' => 'security', 'langcode' => 'en', 'label_d8' => 'Cyber Defense', 'tid_D8' => ''),
            '35268' => array('tid_d7' => '35268', 'label_d7' => 'Security', 'langcode' => 'en', 'label_d8' => 'Cyber Defense', 'tid_D8' => ''),
            '16381' => array('tid_d7' => '16381', 'label_d7' => 'unified communications', 'langcode' => 'en', 'label_d8' => 'Collaborative Workspace', 'tid_D8' => ''),
            '16388' => array('tid_d7' => '16388', 'label_d7' => 'voice and telephony', 'langcode' => 'en', 'label_d8' => 'Collaborative Workspace', 'tid_D8' => ''),
            '33597' => array('tid_d7' => '33597', 'label_d7' => 'welcome to planet local', 'langcode' => 'en', 'label_d8' => '', 'tid_D8' => ''),

            //Solutions FR
            '31988' => array('tid_d7' => '31988', 'label_d7' => 'big data & analytics', 'langcode' => 'fr', 'label_d8' => '', 'tid_D8' => ''),
            '35130' => array('tid_d7' => '35130', 'label_d7' => 'Cloud computing', 'langcode' => 'fr', 'label_d8' => 'IT Flexible', 'tid_D8' => ''),
            '35210' => array('tid_d7' => '35210', 'label_d7' => 'Connectivité', 'langcode' => 'fr', 'label_d8' => 'Connectivité enrichie', 'tid_D8' => ''),
            '20291' => array('tid_d7' => '20291', 'label_d7' => 'conseil et services client', 'langcode' => 'fr', 'label_d8' => 'Service', 'tid_D8' => ''),
            '35073' => array('tid_d7' => '35073', 'label_d7' => 'Digital workspace', 'langcode' => 'fr', 'label_d8' => 'Espaces collaboratifs', 'tid_D8' => ''),
            '35012' => array('tid_d7' => '35012', 'label_d7' => 'Digital workspace', 'langcode' => 'fr', 'label_d8' => 'Espaces collaboratifs', 'tid_D8' => ''),
            '35272' => array('tid_d7' => '35272', 'label_d7' => 'Espaces collaboratifs', 'langcode' => 'fr', 'label_d8' => 'Espaces collaboratifs', 'tid_D8' => ''),
            '18992' => array('tid_d7' => '18992', 'label_d7' => 'Expérience client', 'langcode' => 'fr', 'label_d8' => 'Relation client enrichie', 'tid_D8' => ''),
            '35286' => array('tid_d7' => '35286', 'label_d7' => 'Expérience client', 'langcode' => 'fr', 'label_d8' => 'Relation client enrichie', 'tid_D8' => ''),
            '35146' => array('tid_d7' => '35146', 'label_d7' => 'FR - Digital Transformation eBook Asset Landing Page', 'langcode' => 'fr', 'label_d8' => '', 'tid_D8' => ''),
            '17630' => array('tid_d7' => '17630', 'label_d7' => 'Internet et réseaux', 'langcode' => 'fr', 'label_d8' => '', 'tid_D8' => ''),
            '35171' => array('tid_d7' => '35171', 'label_d7' => 'IoT et data analytics', 'langcode' => 'fr', 'label_d8' => 'Innovation au service du business', 'tid_D8' => ''),
            '33817' => array('tid_d7' => '33817', 'label_d7' => 'Machine to Machine', 'langcode' => 'fr', 'label_d8' => '', 'tid_D8' => ''),
            '34846' => array('tid_d7' => '34846', 'label_d7' => 'Mobilité', 'langcode' => 'fr', 'label_d8' => 'Mobile Workspace', 'tid_D8' => ''),
            '33910' => array('tid_d7' => '33910', 'label_d7' => 'Orange Consulting', 'langcode' => 'fr', 'label_d8' => 'Service', 'tid_D8' => ''),
            '25119' => array('tid_d7' => '25119', 'label_d7' => 'Proche de vous aux 4 coins du monde', 'langcode' => 'fr', 'label_d8' => 'Service', 'tid_D8' => ''),
            '35309' => array('tid_d7' => '35309', 'label_d7' => 'Relation Client Enrichie', 'langcode' => 'fr', 'label_d8' => 'Relation client enrichie', 'tid_D8' => ''),
            '35274' => array('tid_d7' => '35274', 'label_d7' => 'Ressources humaines', 'langcode' => 'fr', 'label_d8' => '', 'tid_D8' => ''),
            '35241' => array('tid_d7' => '35241', 'label_d7' => 'Sécurité', 'langcode' => 'fr', 'label_d8' => 'Cyberdéfense', 'tid_D8' => ''),
            '35173' => array('tid_d7' => '35173', 'label_d7' => 'Transformation digitale', 'langcode' => 'fr', 'label_d8' => '', 'tid_D8' => ''),
            '18335' => array('tid_d7' => '18335', 'label_d7' => 'visioconférence', 'langcode' => 'fr', 'label_d8' => 'Espaces collaboratifs', 'tid_D8' => ''),

            //Solutions RU
            '23250' => array('tid_d7' => '23250', 'label_d7' => 'Аудио- и видеоконференции', 'langcode' => 'ru', 'label_d8' => 'Аудио- и видеоконференции', 'tid_D8' => ''),
            '22351' => array('tid_d7' => '22351', 'label_d7' => 'Безопасность', 'langcode' => 'ru', 'label_d8' => 'Безопасность', 'tid_D8' => ''),
            '22422' => array('tid_d7' => '22422', 'label_d7' => 'Голосовые услуги', 'langcode' => 'ru', 'label_d8' => 'Голосовые услуги', 'tid_D8' => ''),
            '25172' => array('tid_d7' => '25172', 'label_d7' => 'Контакт-центр', 'langcode' => 'ru', 'label_d8' => 'Контакт-центр', 'tid_D8' => ''),
            '23647' => array('tid_d7' => '23647', 'label_d7' => 'Корпоративные сети', 'langcode' => 'ru', 'label_d8' => 'Корпоративные сети', 'tid_D8' => ''),
            '31965' => array('tid_d7' => '31965', 'label_d7' => 'Мобильность', 'langcode' => 'ru', 'label_d8' => 'Мобильность', 'tid_D8' => ''),
            '25166' => array('tid_d7' => '25166', 'label_d7' => 'Облачные вычисления', 'langcode' => 'ru', 'label_d8' => 'Облачные вычисления', 'tid_D8' => ''),
            '25750' => array('tid_d7' => '25750', 'label_d7' => 'Унифицированные коммуникации', 'langcode' => 'ru', 'label_d8' => 'Унифицированные коммуникации', 'tid_D8' => ''),

            //Solutions RU-EN
            '26697' => array('tid_d7' => '26697', 'label_d7' => 'Cloud Computing', 'langcode' => 'ru-en', 'label_d8' => 'Cloud Computing', 'tid_D8' => ''),
            '24129' => array('tid_d7' => '24129', 'label_d7' => 'Conferencing', 'langcode' => 'ru-en', 'label_d8' => 'Conferencing', 'tid_D8' => ''),
            '26699' => array('tid_d7' => '26699', 'label_d7' => 'Connectivity', 'langcode' => 'ru-en', 'label_d8' => 'Connectivity', 'tid_D8' => ''),
            '26703' => array('tid_d7' => '26703', 'label_d7' => 'Contact Centers', 'langcode' => 'ru-en', 'label_d8' => 'Contact Centers', 'tid_D8' => ''),
            '32350' => array('tid_d7' => '32350', 'label_d7' => 'Mobility', 'langcode' => 'ru-en', 'label_d8' => 'Mobility', 'tid_D8' => ''),
            '26695' => array('tid_d7' => '26695', 'label_d7' => 'Security', 'langcode' => 'ru-en', 'label_d8' => 'Security', 'tid_D8' => ''),
            '26257' => array('tid_d7' => '26257', 'label_d7' => 'Unified Communications', 'langcode' => 'ru-en', 'label_d8' => 'Unified Communications', 'tid_D8' => ''),
            '26389' => array('tid_d7' => '26389', 'label_d7' => 'voice and telephony', 'langcode' => 'ru-en', 'label_d8' => 'voice and telephony', 'tid_D8' => ''),
        );
    return $solutions;
}
