<?php

function get_correspondances_soltutionD7_to_thematicD8() {
	$solution_to_thematic =
		array(
			'35144' => array('tid_d7' => '35144', 'label_d7' => 'Digital transformation', 'langcode' => 'en', 'label_d8'=> 'Digital transformation', 'tid_D8' => ''),
			'35173' => array('tid_d7' => '35173', 'label_d7' => 'Transformation digitale', 'langcode' => 'fr', 'label_d8'=> 'Transformation digitale', 'tid_D8' => ''),
		);
	return $solution_to_thematic;
}
