<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\editor\Entity\Editor;

/**
 * Implements hook_form_alter().
 */
function oab_backoffice_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_profil_redacteur_form'
  || $form_id == 'node_profil_redacteur_edit_form'){
    $form['field_social_accounts']['#cardinality_multiple'] = false;

    if (isset($form['field_social_accounts']['widget'])
    && is_array($form['field_social_accounts']['widget'])){
      $form['field_social_accounts']['widget']['#cardinality_multiple'] = false;

      foreach ($form['field_social_accounts']['widget'] AS $key => &$value){
        if (isset($value['value']['#title'])) {
          switch ($key){
            case '0':
              $value['value']['#title'] = t('Twitter account');
              break;
            case '1':
              $value['value']['#title'] = t('LinkedIn account');
              break;
            case '2':
              $value['value']['#title'] = t('Viadeo account');
              break;
            case '3':
              $value['value']['#title'] = t('Google + account');
              break;
          }
          $value['value']['#title_display'] = 'before';
        }
        if (isset($value['_weight'])){
          $value['_weight']['#access'] = false;
        }
      }
    }
  }
}

function oab_backoffice_form_node_container_form_alter(&$form, FormStateInterface $form_state, $form_id)
{
  // on vérifie que le paramètre a été passé dans l'url (id du terme permettant de différencier les types)
  if(isset($_GET['rendering_model_tid'])) {
    $tid = $_GET['rendering_model_tid'];
    $form['field_rendering_model']['widget']['#default_value'] = $tid;
  }
  $form['field_rendering_model']['#disabled'] = TRUE;
}
function oab_backoffice_form_node_container_edit_form_alter(&$form, FormStateInterface $form_state, $form_id)
{
  $form['field_rendering_model']['#disabled'] = TRUE;
}

function oab_backoffice_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match){
  switch ($route_name){
    case 'node.add_page':
      return '<h3>' . t('Please choose a model rendering :') . '</h3>';
      break;
  }
}

function oab_backoffice_ckeditor_css_alter(array &$css, Editor $editor) {
  $css[] = drupal_get_path('theme', 'theme_boosted') . '/css/bootstrap-orange2015.css';
  $css[] = drupal_get_path('theme', 'theme_boosted') . '/css/bootstrap-orange-theme2015.css';
  $css[] = drupal_get_path('theme', 'theme_boosted') . '/css/boosted2015.css';
  $css[] = drupal_get_path('theme', 'theme_boosted') . '/css/font-awesome.css';
  $css[] = drupal_get_path('theme', 'theme_boosted') . '/css/templating/background.css';
  $css[] = drupal_get_path('theme', 'theme_boosted') . '/css/templating/buttons.css';
  $css[] = drupal_get_path('theme', 'theme_boosted') . '/css/templating/shareIcons.css';
  $css[] = drupal_get_path('theme', 'theme_boosted') . '/css/templating/textes.css';
}
