<?php

namespace Drupal\oab_mp_product_formule_packages\Form;

use Drupal\Core\Entity\ContentEntityForm;
use Drupal\Core\Entity\EntityType;
use Drupal\Core\Form\FormStateInterface;
use Drupal\oab_mp_product_formule_packages\Entity\FormulePackageType;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Form controller for Formule package edit forms.
 *
 * @ingroup oab_mp_product_formule_packages
 */
class FormulePackageForm extends ContentEntityForm {

  /**
   * The current user account.
   *
   * @var \Drupal\Core\Session\AccountProxyInterface
   */
  protected $account;


//  function validateForm(array &$form, FormStateInterface $form_state) {
//
////    dd(parent::validateForm($form, $form_state)); // TODO: Change the autogenerated stub
//  }

  /**
   * {@inheritdoc}
   */
  public static function create(ContainerInterface $container) {
    // Instantiates this form class.
    $instance = parent::create($container);
    $instance->account = $container->get('current_user');
    return $instance;
  }


  /**
   * {@inheritdoc}
   */
  public function save(array $form, FormStateInterface $form_state) {
    /** @var \Drupal\oab_mp_product_formule_packages\Entity\FormulePackage $entity */
    $entity = $this->entity;

    // Save as a new revision if requested to do so.
    if (!$form_state->isValueEmpty('new_revision') && $form_state->getValue('new_revision') != FALSE) {
      $entity->setNewRevision();

      // If a new revision is created, save the current user as revision author.
      $entity->setRevisionCreationTime($this->time->getRequestTime());
      $entity->setRevisionUserId($this->account->id());
    }
    else {
      $entity->setNewRevision(FALSE);
    }

    $status = parent::save($form, $form_state);

    switch ($status) {
      case SAVED_NEW:
        $this->messenger()->addMessage($this->t('Created the %label Formule package.', [
          '%label' => $entity->label(),
        ]));
        break;

      default:
        $this->messenger()->addMessage($this->t('Saved the %label Formule package.', [
          '%label' => $entity->label(),
        ]));
    }
    $form_state->setRedirect('entity.formule_package.canonical', ['formule_package' => $entity->id()]);
  }

}
