<?php

use \Drupal\views\ViewExecutable;
use \Drupal\oab_dvi\DviHelper;

function isDVIProduct($node) {
    if ($node->type->entity->get('type') == "product") {
        //initialisation des tid DVI
        $default_labels = array(
            "fr" => array('- 50 salariés', 'Secteur Public'),
            "en" => array('- 50 employees', 'Public Sector')
        );
        $default_values = array();
        foreach ($default_labels as $lang => $labels) {
            $default_values[$lang] = array();
            foreach ($labels as $label) {
                $query = \Drupal::entityQuery('taxonomy_term');
                $query->condition('vid', 'market_segments');
                $query->condition('name', $label);
                $query->condition('langcode', $lang);
                $entity = $query->execute();

                if (!empty($entity)) {
                    $default_values[$lang][] = array_pop($entity);
                }
            }
        }
        $dvi_product = FALSE;
        //on regarde le produit
        if (isset($node->field_market_segment)) {
            //récupération des tag market segment du produit
            $field_market_segment = $node->field_market_segment->getValue();
            if (!empty($field_market_segment) && count($field_market_segment)>0) {
                //pour chaque tag on regarde s'il y en a un dvi
                foreach ($field_market_segment as $values) {
                    if (in_array($values['target_id'], $default_values[$node->language()->getId()])) {
                        $dvi_product = TRUE;
                    }
                }
            }
        }
    }
    return $dvi_product;
}


/**
 * Alteration des form de views
 * @param $form
 * @param $form_state
 * @throws \Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException
 */
function oab_dvi_form_views_exposed_form_alter(&$form, &$form_state) {
    $lang = \Drupal::languageManager()->getCurrentLanguage()->getId();
    /*
     * suppression du filtre produits
    if ($form['#id'] === 'views-exposed-form-subhomes-page-distributor') {

        $query = \Drupal::entityQuery('node');
        $query->condition('status', 1);
        $query->condition('type', 'product');
        $query->condition('field_is_dvi_product', 1);
        $query->condition('langcode', $lang);
        $entity_ids = $query->execute();

        $nodes = \Drupal::entityTypeManager()->getStorage('node')->loadMultiple($entity_ids);

        $options = array();
        $options[""] = "Produits";
        foreach ($nodes as $node) {
            $options[$node->id()] = $node->label();
        }

        $formProducts = [
            "#type"             => 'select',
            '#options'          => $options,
            "#size"             => NULL,
            '#default_value'    => '',
            '#validated'        => TRUE
        ];
        $form['product'] = $formProducts;
    }
    */


    //Subhome Products DVI
    if ($form['#id'] == 'views-exposed-form-subhomes-page-catalogue-dvi') {
        $form['#attributes']['class'][] = "hidden";
    }
}
