<?php

use \Drupal\views\ViewExecutable;
use \Drupal\oab_dvi\DviHelper;

function isDVIProduct($node){
	if($node->type->entity->get('type') == "product"){
		//initialisation des tid DVI
		$default_labels = array(
			"fr" => array('- 50 salariés', 'Secteur Public'),
			"en" => array('- 50 employees', 'Public Sector')
		);
		$default_values = array();
		foreach ($default_labels as $lang => $labels)
		{
			$default_values[$lang] = array();
			foreach ($labels as $label) {
				$query = \Drupal::entityQuery('taxonomy_term');
				$query->condition('vid', 'market_segments');
				$query->condition('name', $label);
				$query->condition('langcode', $lang);
				$entity = $query->execute();

				if (!empty($entity)) {
					$default_values[$lang][] = array_pop($entity);
				}
			}
		}
		$dvi_product = FALSE;
		//on regarde le produit
		if (isset($node->field_market_segment)) {
			//récupération des tag market segment du produit
			$field_market_segment = $node->field_market_segment->getValue();
			if (!empty($field_market_segment) && count($field_market_segment)>0) {
				//pour chaque tag on regarde s'il y en a un dvi
				foreach ($field_market_segment as $values){
					if(in_array($values['target_id'], $default_values[$node->language()->getId()])){
						$dvi_product = TRUE;
					}
				}
			}
		}
	}
	return $dvi_product;
}

function oab_dvi_views_pre_view(ViewExecutable $view, $display_id, array &$args) {


    if ($view->id() == "subhomes" &&
        ($display_id == "page_catalogue" ||$display_id == "page_catalogue_dvi")  ) {
        $request = $view->getRequest();

        $segmentParameter = $request->query->get('segment');
        if (DviHelper::isMSTerm($segmentParameter)) {
            $tid = DviHelper::getMSTaxoTermId($segmentParameter);
            $request->query->set('segment', $tid);
        }
    }
}