<?php

/**
 * @file
 * Contains oab_mp_formules.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\file\Entity\File;
use Drupal\media\Entity\Media;
use Drupal\node\NodeInterface;
use Drupal\paragraphs\Entity\Paragraph;

/**
 * Implements hook_help().
 */
function oab_mp_formules_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the oab_mp_formules module.
    case 'help.page.oab_mp_formules':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Manage the Product Formule entity') . '</p>';
      return $output;

    default:
  }

}


function oab_mp_formules_theme($existing, $type, $theme, $path) {
  return [
    'product_formule_entity' => [
      'render element' => 'elements',
    ],
  ];
}


function oab_mp_formules_preprocess_product_formule_entity(array &$variables) {

  /** @var \Drupal\oab_mp_formules\Entity\ProductFormuleEntity $product_formule */
  $product_formule = $variables['elements']['#product_formule_entity'];
  $variables['product_formule_entity'] = $product_formule;
//
  foreach ($product_formule->getFormuleFields() as $formule_field) {
    $variables['formule_fields'][] = \Drupal::entityTypeManager()->getViewBuilder('formule_field')->view($formule_field);
  }

  if ($product_formule->hasField("field_illustration")) {
    $product_formule_illustration = Media::load($product_formule->field_illustration->target_id ?? 0);
    $image = File::load($product_formule_illustration ?->field_image->target_id ?? 0);
    $variables['field_illustration_uri'] = $image ?->getFileUri();
    $variables['field_illustration_alt'] = $product_formule_illustration ?->field_image ?->alt;
  }

  $node = \Drupal::routeMatch()->getParameter('node');

  if ($node instanceof NodeInterface) {
    $variables['node_label'] = $node->hasField('field_product_name')
      ? $node->field_product_name->value
      : $node->getTitle();
  }

}
