<?php


/**
 * Ajout des traductions FR de la page CSP
 */
oabt_TranslationImport("Availability in France","fr","Disponibilité France");
oabt_TranslationImport("France and International Availability","fr","Disponibilité France et international");
oabt_TranslationImport("International availability","fr","Disponibilité international");
oabt_TranslationImport("No technical qualification","fr","Pas de qualification technique");
oabt_TranslationImport("Technical standard qualification","fr","Qualification technique standard");
oabt_TranslationImport("Technical study required","fr","Etude technique nécessaire");
oabt_TranslationImport("Access to a dedicated infrastructure","fr","Accès à une infrastructure dédiée");
oabt_TranslationImport("Access to a shared cloud service","fr","Accès à un service cloud partage");
oabt_TranslationImport("Business VPN Galerie offers a connection to these cloud services at the following speeds","fr","Business VPN Galerie vous propose une connexion à ces services cloud aux débits suivants");
oabt_TranslationImport("This service is billed according to your number of sites","fr","Ce service est facturé selon votre nombre de sites");
oabt_TranslationImport("This service is charged according to your number of users","fr","Ce service est facturé selon votre nombre d’utilisateurs ");



