css:
  brotli: false
  fix_type: true
  combine_media: false
  preserve_external: false
path:
  convert:
    force_https: false
    absolute: false
    absolute_to_protocol_relative: false
enabled: false
dns_prefetch: false
cache_level: 2
cron_frequency: 900
js:
  brotli: false
  fix_type: true
  preserve_external: false
immutable: false
symlinks: false
symlinksifownermatch: false
