axiome_enable_cron: '1'
icon_frame_connectivity: Connectivity
icon_frame_teamwork: Teamwork
icon_frame_my_customers: Customers
icon_frame_performance: Flexibility
icon_frame_security: Security
icon_frame_care: Service
icon_frame_tech: Industry
sous_famille_values:
  8391: 'Solutions de communication et collaboration'
  8407: Exécution
  8471: ' Infrastructures'
  8502: 'Accompagnement et expertises'
  9369: 'Intelligent networking'
  8528: 'Select and configure connected objects'
  8500: ' Infrastructures'
  8501: 'Développement et management des applications'
  10205: 'Analyse Conseil'
  10215: 'Comprendre vos clients pour mieux les servir'
  8457: 'Réseaux intelligents'
  8461: 'Réseaux intelligents'
  9058: 'Réseaux intelligents'
  9215: Integration
  8964: 'Solutions de communication et collaboration'
  8389: 'Réseaux intelligents'
  8276: 'Services clients'
  8614: 'Services clients'
  8398: 'Applications métiers et productivité'
  8506: 'Communication and collaboration'
  8520: 'Communication and collaboration'
  8851: ' Infrastructures'
  8468: 'Développement et management des applications'
  8416: Integration
  8531: Execution
  8532: Execution
  10389: 'Solutions de communication et collaboration'
  10390: 'Select and configure connected objects'
  8711: 'Choisir et configurer les objets connectés'
  8492: 'Solutions de communication et collaboration'
  8550: 'Solutions de communication et collaboration'
  10447: Protect
  8279: 'Réseaux intelligents'
  8541: 'Select and configure connected objects'
  10486: Respond
  8406: 'Services clients'
  8519: Execution
  9218: Détecter
  10566: Identifier
  8619: 'Performance client'
  8399: 'Protéger (suite)'
  9829: 'Services clients'
  10606: 'Améliorer les processus métier'
  8555: Protéger
  8551: Exécution
  8278: 'Comprendre vos clients pour mieux les servir'
  8514: 'Contact Centers'
  8413: Exécution
  8393: 'Solutions de communication et collaboration'
  8587: Protect
  8395: 'Développement et management des applications'
  8397: Identifier
  8400: 'Accompagnement et expertises'
  8513: Integration
  9272: Execution
  8833: 'Services clients'
  8270: 'Equipements et solutions de connectivité mobile'
  8615: 'Services clients'
  8460: 'Services clients'
  10897: 'Communication and collaboration'
  8535: 'Communication and collaboration'
  8498: 'Piloter les objets connectés'
  8503: 'Solutions de communication et collaboration'
  10925: 'Protéger (suite)'
  10941: 'Intelligent networking'
  10942: 'Intelligent networking'
  8455: 'Connectivité multi-cloud simple et sécurisée'
  9716: 'Solutions de communication et collaboration'
  8526: 'Simple and secure multi-cloud connectivity'
  8466: 'Réseaux intelligents'
  8470: 'Applications digitales'
  10948: 'Solutions de communication et collaboration'
  8493: 'Services clients'
  8257: Intégration
  8571: 'Applications digitales'
  8516: 'Support and expertise'
  8533: Detect
  8987: 'Communication and collaboration'
  11007: 'Identifier (suite)'
  11011: Réagir
  11048: Detect
  8283: 'Comprendre vos clients pour mieux les servir'
  8572: 'Services clients'
  11095: Anticipate
  8505: Protect
  8510: Protect
  8512: Protect
  8527: Detect
  8265: 'Réseaux intelligents'
  8401: 'Solutions de communication et collaboration'
  8463: 'Protéger (suite)'
  11200: 'Solutions de communication et collaboration'
  11243: 'Maitriser les risques'
  11276: 'Analyse Conseil'
  8277: 'Protéger (suite)'
  8281: Réagir
  8396: 'Protéger (suite)'
  8287: Détecter
  9059: Détecter
  11292: Identify
  8507: 'Communication and collaboration'
  8473: 'Intelligent networking'
  8530: 'Collaborative Solutions'
  8534: 'Communication and collaboration'
  8824: Protect
  11326: Consulting
  8269: 'Services clients'
  9002: Protect
  11707: 'Contact Centers'
