<?php


function oab_orange_business_lounge_theme($existing, $type, $theme, $path) {

    return array(
        'orange_business_lounge_page_zone' =>
            array(
                'variables' => array(
                    'zones' => array(),
                    'countriesWithOperators' => array(),
                    'detail_accords' => array(),
                    'techno' => '0',
                    'pager' => array()
                ),
                'template' => 'obl_template'
            ),

        'orange_business_lounge_page_pays' =>
            array(
                'variables' => array(
                    'countries' => array(),
                    'zones' => array(),
                    'zones_image' => array(),
                    'pass_data' => array(),
                    'network_data' => array(),
                ),
                'template' => 'obl_prices_template'
            ),
        );
}


function oab_orange_business_lounge_preprocess_pager(&$variables) {
//  kint($variables);
  if (isset($variables['pager']['#page_id']) && $variables['pager']['#page_id'] === 'obl_controller') {
    unset($variables['items']['previous']);
    $variables['items']['next']['text'] = '›';
  }
}
