<?php

/**
 * MAJ de la view subhomes
 */
function oab_subhomes_update_8001()
{
    oabt_YmlImport('views.view.subhomes.yml');
}

/**
 * Création des fields + display form de l'entité Presse
 */
function oab_subhomes_update_8002() {
    include_once('updates/update_8002.inc');
}

/**
 * Rechargement des views et création d'un field pour les press kits
 */
function oab_subhomes_update_8003() {
    include_once('updates/update_8003.inc');
}
