<?php

/**
 * @file
 * Contains oab_subhomes.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\oab_subhomes\Entity\SubhomeEntity;
use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Access\AccessResult;

/**
 * Implements hook_help().
 */
function oab_subhomes_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the oab_subhomes module.
    case 'help.page.oab_subhomes':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for subhomes entity generation') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function oab_subhomes_theme($existing, $type, $theme, $path) {

    $theme = [];
    $theme['subhome_entity'] = [
        'render element' => 'elements',
        'path' => drupal_get_path('theme', 'theme_boosted') . '/templates/subhome_entity',
        'theme path'    => drupal_get_path('theme', 'theme_boosted') ,
        'template' => 'subhome_entity',
        'type'  => 'module',
    ];
    $theme['paragraph'] = [
        'render element' => 'elements',
        'path' => drupal_get_path('theme', 'theme_boosted') . '/templates/paragraphs',
        'theme path'    => drupal_get_path('theme', 'theme_boosted') ,
        'template' => 'paragraph',
        'type'  => 'module',
    ];
    $theme['subhome_entity_content_add_list'] = [
        'render element' => 'content',
        'variables' => ['content' => NULL],
        'file' => 'subhome_entity.page.inc',
    ];
    return $theme;
}

function oab_subhomes_preprocess_subhome_entity(&$variables) {
  /** @var Drupal\oab_subhomes\Entity\SubhomeEntity $subhome_entity */
    $subhome_entity = $variables['elements']['#subhome_entity'];
    foreach (\Drupal\Core\Render\Element::children($variables['elements']) as $key) {
        $variables['content'][$key] = $variables['elements'][$key];
    }
}


/**
* Implements hook_theme_suggestions_HOOK().
*/
function oab_subhomes_theme_suggestions_subhome_entity(array $variables) {
    $suggestions = [];
    $entity = $variables['elements']['#subhome_entity'];
    $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

    $suggestions[] = 'subhome_entity__' . $sanitized_view_mode;
    $suggestions[] = 'subhome_entity__' . $entity->bundle();
    $suggestions[] = 'subhome_entity__' . $entity->bundle() . '__' . $sanitized_view_mode;
    $suggestions[] = 'subhome_entity__' . $entity->id();
    $suggestions[] = 'subhome_entity__' . $entity->id() . '__' . $sanitized_view_mode;
    return $suggestions;
}

function oab_subhomes_theme_suggestions_views_view_alter(array &$suggestions, array $variables) {
    /**
     * @var Drupal\views\ViewExecutable $view
     * @var SubhomeEntity $entity
     */

    if (isset($variables['view'])) {
        $view = $variables['view'];
        if ($view->id() == 'subhomes' && isset($view->argument['field_subhome_target_id'])) {

            $sid = $view->argument['field_subhome_target_id']->value;
            $entity = SubhomeEntity::loadBySubhomeId($sid);

            // Si on a trouvé une entité pour la subhome, on la load et on la passe à la vue
            if ($entity !== null) {
                $suggestions[] = 'views_view__subhomes__' . $entity->bundle();
            }
        }
    }
}


function oab_subhomes_palette_orange_allowed_values_function(FieldStorageConfig $definition, ContentEntityInterface $entity = NULL,
                                                         $cacheable) {
    $allowedValues = array (
        "black-on-orange"   => "Black on Orange",
        "white-on-orange"   => "White on Orange",
        "orange-on-white"   => "Orange on White",
        "black-on-white"    => "Black on White",
        "grey-on-white"     => "Grey on White",
        "orange-on-black"   => "Orange on Black",
        "white-on-black"    => "White on Black",
        "grey-on-black"     => "Grey on Black",
        "white-on-obs-grey"  => "White on OBS Grey",
        "black-on-yellow"   => "Black on Yellow",
        "black-on-blue"     => "Black on Blue",
        "black-on-green"    => "Black on Green",
        "black-on-purple"   => "Black on purple",
        "black-on-pink"     => "Black on pink"
    );
    return $allowedValues;
}

function oab_subhomes_btn_allowed_values_function(FieldStorageConfig $definition, ContentEntityInterface $entity = NULL,
                                     $cacheable) {
    $allowedValues = array (
        "btn-txt-white-bg-black"   => "Texte blanc, fond noir",
        "btn-txt-white-bg-transparent"   => "Texte blanc, fond transparent",
        "btn-txt-black-bg-white"   => "Texte noir, fond blanc",
        "btn-txt-black-bg-transparent"    => "Texte noir, fond transparent",
        "btn-txt-white-bg-orange"   => "Texte blanc, fond orange",
        "btn-txt-black-bg-orange"   => "Texte noir, fond orange"
    );
    return $allowedValues;
}

function oab_subhomes_preprocess_views_view(&$variables) {

    /** @var Drupal\views\ViewExecutable $view */
    $view = $variables['view'];
    $id = $view->storage->id();

    if ($id == 'subhomes') {

        /*
         * Nouvelle gestion des subhomes
         * Je passe en variable l'entité subhome correspondante
         */
        if (isset($view->argument['field_subhome_target_id'])) {

            $sid = $view->argument['field_subhome_target_id']->value;
            $entity = SubhomeEntity::loadBySubhomeId($sid);

            // Si on a trouvé une entité pour la subhome et qu'elle est de type presse, je load les press_kits de la langue
            if ($entity !== null && $entity->bundle() === 'presse') {
                /** @var Drupal\node\Entity\Node[] $entities */
                /*$entities = \Drupal::entityTypeManager()->getStorage('node')
                    ->loadByProperties([
                        'type'=> 'press_kit',
                        'langcode' => $entity->language()->getId(),
                        'status' => true
                    ]);*/

                $query = \Drupal::entityQuery('node')
                    ->condition('status', 1)
                    ->condition('type', 'press_kit')
                    ->condition('langcode', $entity->language()->getId())
                    ->sort('changed' , 'DESC');

                $nids = $query->execute();
                $entities = \Drupal::entityTypeManager()->getStorage('node')
                    ->loadMultiple($nids);

                $view_builder = \Drupal::entityTypeManager()->getViewBuilder('node');
                foreach ($entities as $entity ) {
                    $variables[SubhomeEntity::TWIG_VAR_NAME]['press_kit'][] =
                        render($view_builder->view($entity, 'subhome'));
                }
            }
        }
    }
}


/**
 * HOOK_ENTITY_ACCESS
 *
 * Problèmes de droits pour les paragraphes utilisés dans la refonte de la subhome press. Je donne l'accès pour les voir
 */
function oab_subhomes_entity_access(EntityInterface $entity, $operation, AccountInterface $account) {
    if ($entity->getEntityTypeId() == 'paragraph'
        && ($entity->bundle() === 'subhome_presse_carrousel' || $entity->bundle() === 'default_button')
        && $operation == 'view'
    ) {
        return AccessResult::allowed();
    }

    return AccessResult::neutral();
}
