<?php


/*
 * RUBYPORTAILOBS-2722 rajout daste par defaut au champs de publication
 */

oabt_YmlImport('field.field.node.blog_post.field_start_date.yml');
oabt_YmlImport('field.field.node.customer_story.field_start_date.yml');
oabt_YmlImport('field.field.node.document.field_start_date.yml');
oabt_YmlImport('field.field.node.full_html.field_start_date.yml');
oabt_YmlImport('field.field.node.magazine.field_start_date.yml');
oabt_YmlImport('field.field.node.partner.field_start_date.yml');
oabt_YmlImport('field.field.node.press_kit.field_start_date.yml');
oabt_YmlImport('field.field.node.press_release.field_start_date.yml');
oabt_YmlImport('field.field.node.product.field_start_date.yml');
oabt_YmlImport('field.field.node.simple_page.field_start_date.yml');
