<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_field_widget_form_alter().
 */
function oab_modular_product_field_widget_form_alter(&$element, FormStateInterface $form_state, $context) {
  /*
   * Ici, on ne va gérer que les alterations du formulaire du paragraph
   */
  if (!isset($element['#paragraph_type']) ) {
    return;
  }

  /** @var \Drupal\oab_modular_product\Services\OabModularProductService $conf_modular_product */
  $conf_modular_product = \Drupal::service('oab_modular_product.settings');
  $modules = [
    'module_benefits',
    'module_3_4_colonnes'
  ];

  $module_items = [
    'module_benefits_item',
    'module_3_4_colonnes_items',
    'module_detail_offre_items'
  ];

  if ($element['#paragraph_type'] == 'module_partner') {
    $element['subform']['field_title']['widget'][0]['value']['#maxlength'] = 65;
    $element['subform']['field_highlight']['widget'][0]['value']['#maxlength'] = 150;

  }

  if (in_array($element['#paragraph_type'], $modules)) {
    if (isset($element['subform']['field_title'])) {
      $element['subform']['field_title']['widget'][0]['value']['#maxlength'] = $conf_modular_product->getModuleTitleMaxCharacter();
      $element['subform']['field_title']['widget'][0]['value']['#size'] = 75;
    }

    if (isset($element['subform']['field_accroche'])) {
      $element['subform']['field_accroche']['widget'][0]['value']['#maxlength'] = $conf_modular_product->getModuleDescriptionMaxCharacter();
    }

    if (isset($element['subform']['field_highlight'])) {
      $element['subform']['field_highlight']['widget'][0]['value']['#maxlength'] = $conf_modular_product->getModuleDescriptionMaxCharacter();
      $element['subform']['field_highlight']['widget'][0]['value']['#rows'] = 2;
    }
  }

  if (in_array($element['#paragraph_type'], $module_items)) {
    if (isset($element['subform']["field_icon"])) {
      $element['subform']["field_icon"][0]['token_tree'] = [
        '#theme' => 'token_tree_link',
        '#token_types' => ['icomoon'],
        '#weight' => 90,
        '#global_types' => FALSE,
        '#click_insert' => TRUE,
      ];
    }

    if (isset($element['subform']['field_title'])) {
      $element['subform']['field_title']['widget'][0]['value']['#maxlength'] = $conf_modular_product->getModuleItemsTitleMaxCharacter();
      $element['subform']['field_title']['widget'][0]['value']['#size'] = 80;
    }

    if (isset($element['subform']['field_accroche'])) {
      $element['subform']['field_accroche']['widget'][0]['value']['#maxlength'] = $conf_modular_product->getModuleItemsDescriptionMaxCharacter();
    }

    if (isset($element['subform']['field_description'])) {
      $element['subform']['field_description']['widget'][0]['value']['#maxlength'] = $conf_modular_product->getModuleItemsDescriptionMaxCharacter();
      $element['subform']['field_description']['widget'][0]['value']['#size'] = 140;
    }
  }

  if ($element['#paragraph_type'] === 'module_step') {
    $element['subform']['field_title']['widget'][0]['value']['#maxlength'] = 30;
    $element['subform']['field_title']['widget'][0]['value']['#size'] = 35;

    $element['subform']['field_description']['widget'][0]['value']['#maxlength'] = 100;
    $element['subform']['field_description']['widget'][0]['value']['#size'] = 110;
  }

}

/**
 * Implements hook_form_alter().
 */
function oab_modular_product_form_node_modular_product_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  /** @var \Drupal\oab_modular_product\Services\OabModularProductService $conf_modular_product */
  $conf_modular_product = \Drupal::service('oab_modular_product.settings');

  if (isset($form['field_product_name'])) {
    $form['field_product_name']['widget'][0]['value']['#maxlength'] = $conf_modular_product->getTopZoneTitleMaxCharacter();
  }

  if (isset($form['field_teaser'])) {
    $form['field_teaser']['widget'][0]['value']['#maxlength'] = $conf_modular_product->getTopZoneDescriptionMaxCharacter();
  }

}

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function oab_modular_product_entity_bundle_field_info_alter(&$fields, \Drupal\Core\Entity\EntityTypeInterface $entity_type, $bundle) {
  if ($entity_type->id() === "paragraph" && $bundle === "module_steps") {
    $fields['field_step']->addConstraint('ModularProductMinSteps');
  }
}



/**
 * Implements hook_preprocess_HOOK().
 */
function oab_modular_product_preprocess_field(&$variables) {

  if ($variables['field_name'] !== "field_link_button"
    || $variables['entity_type'] !== "paragraph") {
    return;
  }

  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['element']['#object'];

  if (isset($paragraph->field_call_to_action_type)) {
    $variables['link_type'] = $paragraph->field_call_to_action_type->value;

    if ($paragraph->field_call_to_action_type->value === "lien") {
      /** @var \Drupal\Core\Field\FieldItemListInterface $field_link_button */
      $field_link_button = $paragraph->field_link_button;

      /** @var \Drupal\link\Plugin\Field\FieldType\LinkItem $link_item */
      $link_item =$field_link_button->first();

      if ($link_item->isExternal()) {
        $variables['attributes']['class'][] = 'icon-Redo font-weight-bold';
      }
      else {
        $variables['attributes']['class'][] = 'o-link-arrow text-decoration-none';
      }
    }
    else {
      $variables['attributes']['class'][] = 'btn btn-primary';
    }
  }
}

