<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function oab_modular_product_field_widget_paragraphs_form_alter(&$element, FormStateInterface $form_state, $context) {
  if ($element['#paragraph_type'] == 'module_benefits_item') {
     $element['subform']["field_icon"][0]['token_tree'] = [
       '#theme' => 'token_tree_link',
       '#token_types' => ['icon_orange'],
       '#weight' => 90,
       '#global_types' => FALSE,
       '#click_insert' => TRUE,
     ];
   }
}
/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 */
function oab_modular_product_field_widget_entity_reference_paragraphs_form_alter(&$element, &$form_state, $context) {
  if ($element['#paragraph_type'] == 'module_text_video_image') {

    $element['subform']['field_visual']['#states'] = [
      'visible' => [
        ':input[name="field_modules[0][subform][field_media_type]"]' => ['value' => 'image'],
      ],
      'required' => [
        ':input[name="field_modules[0][subform][field_media_type]"]' => ['value' => 'image'],
      ]
    ];
    $element['subform']['field_video']['#states'] = [
      'visible' => [
        ':input[name="field_modules[0][subform][field_media_type]"]' => ['value' => 'video'],
      ],
      'required' => [
        ':input[name="field_modules[0][subform][field_media_type]"]' => ['value' => 'video'],
      ]
    ];

  }
}
/**
 * Implements hook_form_alter().
 */
/*
function oab_modular_product_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  if (in_array($form, array('node_modular_product_edit_form', 'node_modular_product_form'))) {

  }
}*/
