<?php

function oab_yassine_install() {
    drupal_set_installed_schema_version('oab_yassine', 8000);
}


/** Définit l'ordre des updates par rapport aux autres modules
 * @return mixed
 */
function oab_yassine_update_dependencies() {
  $dependencies['oab_yassine'][8001] = array('oab_christophe' => 8020	);

  return $dependencies;
}

/**
 *  Ajout du module de sélection de couleur dans le wysiwyg
 */
function oab_yassine_update_8001() {
  include_once("updates/update_8001.inc");
}
