<?php

oabt_YmlImport('metatag.metatag_defaults.node__country.yml');
oabt_YmlImport('metatag.metatag_defaults.node__full_html.yml');
oabt_YmlImport('metatag.metatag_defaults.node__homepage.yml');
oabt_YmlImport('metatag.metatag_defaults.node__homepage_eclairage.yml');
oabt_YmlImport('metatag.metatag_defaults.node__hp_eclairage_thematique.yml');
oabt_YmlImport('metatag.metatag_defaults.node__industry.yml');
oabt_YmlImport('metatag.metatag_defaults.node__region.yml');
oabt_YmlImport('metatag.metatag_defaults.node__solution.yml');