
<?php

// ajout du field display title
oabt_YmlImport("field.field.node.distributor.field_display_title.yml");

// ajout du field header title pour le titre plus long
oabt_YmlImport("field.field.node.distributor.field_header_title.yml");

//mise a jour des form display et view display
oabt_YmlImport("core.entity_form_display.node.distributor.default.yml");
oabt_YmlImport("core.entity_view_display.node.distributor.default.yml");

//settings language distributeur
oabt_YmlImport("language.content_settings.node.distributor.yml");