<?php

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Markup;
use Drupal\Core\Url;
use Drupal\node\NodeForm;
use Drupal\node\NodeInterface;
use Drupal\oab_tokens\Entity\NodeToken;
use Drupal\node\Entity\Node;
use Drupal\oab_tokens\Services\NodeTokenService;
use Drupal\Core\Session\AccountInterface;
/**
 * Implements hook_form_alter().
 */
function oab_tokens_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_state->getFormObject() instanceof NodeForm) {
    /** @var Node $node */
    $node = $form_state->getFormObject()->getEntity();
    // si le node est en draft (nouveau ou état actuel draft)
    if ((isset($node->moderation_state->value) && $node->moderation_state->value == "draft")
      || $node->status->value === 0) {

      /** @var NodeTokenService $node_token_service */
      $node_token_service =  Drupal::service('oab_tokens.node_token_service');
      $token = $node_token_service->getToken($node);
      if (isset($token->token->value)) {
        $url = Url::fromRoute('entity.node.revision', ['node' => $node->id(), 'node_revision' => $node->getRevisionId()]);
        $url_node_token = \Drupal::service('path_alias.manager')->getAliasByPath($url->toString()). '?token=' . $token->token->value;
      }
      //ajout de la case à cocher pour la génération du token
      $form['generate_token_url'] = [
        '#title' => t('Generate shared URL'),
        '#type' => 'checkbox',
        "#group" => "footer",
        '#disabled' => !empty($token),
        '#default_value' => !empty($token)
      ];
      $form['actions']['submit']['#submit'][] = '_oab_tokens_node_form_submit';
    }
  }
}
function _oab_tokens_node_form_submit(&$form, FormStateInterface $form_state) {
  if ($form_state->getValue('generate_token_url') === 1) {
    /** @var NodeTokenService $node_token_service */
    $node_token_service =  Drupal::service('oab_tokens.node_token_service');
    /** @var Node $node */
    $node = $form_state->getFormObject()->getEntity();
    $token = $node_token_service->getToken($node);
    if (!isset($token)) {
      $token = $node_token_service->createNodeToken($node);
    }
  }
}


function oab_tokens_node_access(EntityInterface $entity, $operation, AccountInterface $account) {
  if (in_array($operation, ['view', 'view revision'])) {
    /** @var Node $node */
    if (Drupal::routeMatch()->getParameter('node_revision') !== NULL) {
      $node = Drupal::routeMatch()->getParameter('node_revision');
    } else {
      $node = Drupal::routeMatch()->getParameter('node');
    }
    if (isset($node) &&
      ((isset($node->moderation_state->value) && $node->moderation_state->value == "draft")
      || $node->status->value === 0)) {
      $token = \Drupal::request()->query->get('token');
      if (isset($token)) {
        if (\Drupal::service('oab_tokens.node_token_service')->isValidToken($node->id(), $node->vid->value, $token)) {
          return AccessResult::allowed();
        }
        else {
          return AccessResult::forbidden();
        }
      }
    }
  }
  return AccessResult::neutral();
}

function oab_tokens_node_predelete(NodeInterface $node) {
  //on supprime les token liés à ce node avant sa suppression
  /** @var NodeTokenService $node_token_service */
  $node_token_service =  Drupal::service('oab_tokens.node_token_service');
  $node_token_service->deleteNodeTokenForNode($node);
}

function oab_tokens_node_update(NodeInterface $node) {
  /** @var NodeTokenService $node_token_service */
  $node_token_service =  Drupal::service('oab_tokens.node_token_service');
  if ((isset($node->moderation_state->value) && $node->moderation_state->value == "draft")
    || $node->status->value === 0) {
    //si le node est toujours Draft, on met à jour le numéro de version sur le node token (la révision est créée a chaque enregistrement
    $node_token_service->updateRevisionForNodeToken($node);
  } else {
    //le node n'est plus draft, on supprime ses tokens
    $node_token_service->deleteAllNodeTokenForNode($node);
  }
}


function oab_tokens_node_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if($build['#view_mode'] === "full" && $entity instanceof NodeInterface) {
    /** @var NodeTokenService $node_token_service */
    $node_token_service =  Drupal::service('oab_tokens.node_token_service');
    $token = $node_token_service->getToken($entity);
    if (isset($token->token->value)) {
      //l'url de la révision
      $url = Url::fromRoute('entity.node.revision', ['node' => $entity->id(), 'node_revision' => $entity->getRevisionId(), 'token' => $token->token->value])
        ->setAbsolute()
        ->toString();
      // on supprime le backoffice. au cas où il soit présent
      if (str_contains($url, 'backoffice.')) {
        $url = str_replace('backoffice.', '', $url);
      }
      //on fait un message d'information qui contient l'url prête à être copiée
      \Drupal::messenger()->addMessage(Markup::create(t("Shared URL"). " : $url  <a class='btn-sm btn-icon' data-href='$url' onclick='copyToClipboard(this)'><span class='sr-only'>Icon</span> <span class='icon icon-copy' aria-hidden='true'></span></a>"));
      $build['#attached']['library'][]  = 'oab_tokens/tokens';
    }
  }
}
