<?php
use Symfony\Component\Yaml\Yaml;


/*
 * RUBYPORTAILOBS-3195 traduction du pager du moteur de recherche
 */

oabt_TranslationImport("previous","fr","précédent");
oabt_TranslationImport("Previous page","fr","Page précédente");
oabt_TranslationImport("Go to previous page","fr","Aller à la page précédente");
oabt_TranslationImport("next","fr","suivant");
oabt_TranslationImport("Next page","fr","Page suivante");
oabt_TranslationImport("Go to next page","fr","Aller à la page suivante");

