<?php

use Drupal\oab_hub\Controller\OabHubController;

/**
 * Pour le formulaire d'ajout d'une taxo Hub, je n'affiche que les subhomes de la langue en cours
 */
function oab_hub_form_taxonomy_term_hub_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    $current_language = \Drupal::languageManager()->getCurrentLanguage()->getId();
    $tids = array_keys($form[OabHubController::FIELD_SUBHOMES_ID]['widget']['#options']);
    $terms = \Drupal\taxonomy\Entity\Term::loadMultiple($tids);
    foreach ($terms as $term) {
        $lang = $term->language();
        if ( $lang->getId() != $current_language ) {
            unset($form[OabHubController::FIELD_SUBHOMES_ID]['widget']['#options'][$term->id()]);
        }
    }
}


/**
 * Surcharge de la fonction oabt_YmlImport pour adapter au module
 * (changement des variables par défaut pour éviter de les remettre à chaque fois)
 */
function oab_hub_ymlImport($file_name,$dir_name="/",$module_name="oab_hub") {
    oabt_YmlImport($file_name,$dir_name,$module_name);
}


/**
 * hook_ENTITY_TYPE_insert
 * Hook pour créer les menus/blocks à la création d'un taxo HUB
 */
function oab_hub_taxonomy_term_insert(\Drupal\taxonomy\Entity\Term $term) {

    ##on ne le fait que pour la création des termes pour le HUB
    if ($term->getVocabularyId() == OabHubController::HUB_VOCABULARY_ID) {
        OabHubController::createMachineNameSuffixe($term);
        OabHubController::createMenus($term);
        //OabHubController::createBlocks($term);
    }
}

/**
 * suppression des menus à la suppression d'un terme
 */
function oab_hub_taxonomy_term_delete(\Drupal\taxonomy\Entity\Term $term)  {
    if ($term->getVocabularyId() == OabHubController::HUB_VOCABULARY_ID) {
        OabHubController::deleteMenus($term);
        //OabHubController::deleteBlocks($term);
    }
}

/**
 * Lors de l'ajout d'une traduction à un taxo HUB, je fais comme pour la création d'un nouveau term
 */
/*function oab_hub_taxonomy_term_translation_create(\Drupal\taxonomy\Entity\Term $translation) {
    if ($translation->getVocabularyId() == OabHubController::HUB_VOCABULARY_ID) {
        //\Drupal::logger('oab_hub')->notice('Coucou c est moi');
        kint($translation); die();
        OabHubController::createMenus($translation);
        //OabHubController::createBlocks($term);
    }
}

function oab_hub_taxonomy_term_translation_delete(\Drupal\taxonomy\Entity\Term $translation) {
    if ($translation->getVocabularyId() == OabHubController::HUB_VOCABULARY_ID) {
        OabHubController::deleteMenus($translation);
        //OabHubController::deleteBlocks($term);
    }
}
*/

